---
openapi: 3.0.0
info:
  title: Social Media App API
  description: This is a simple API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/lukmanhafidz/SocialMediaAppAPI/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Authentication
  description: Layanan untuk authentikasi user
- name: User
  description: Layanan yang mengorganisir data user
- name: Posting
  description: Layanan yang mengorganisir data posting
- name: Comment
  description: Layanan yang mengorganisir data comment
  
paths:
  /login:
    post:
      tags:
      - Authentication
      summary: ini fitur login
      description: Menambahkan data user baru
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModelUser'
            example:
              username: JohnKecoak
              password: John123
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelUser'
              example:
                code: 200
                message: Login success
                token: $3gjk2UHkndlAubdDiHOjnD238Dijk
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelUser'
              example:
                code: 400
                message: Wrong username or password
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
  /user:
    get:
      tags:
      - User
      summary: ini fitur lihat data user
      description: Tampilkan data user yang login
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelUser'
              example:
                id: 1
                fotoprofil: alex.jpg
                firstname: Alex
                lastname: Capung
                username: DragonAlex
                posts:
                - postid: 1
                  foto: foto.jpg
                  caption: Rusia menyalakan bom nuklir, begini tanggapan Lesti Billar
                  created_at: 2022-09-11T12:40:00Z
                  comments:
                  - commentid: 1
                    firstname: Jenny
                    lastname: Nyamuk
                    fotoprofil: jenny.jpg
                    comment: Bagus Banget kak
                    created_at: 2022-09-11T12:40:00Z
                  - commentid: 2
                    firstname: Gerrad
                    lastname: Beruang
                    fotoprofil: Gerrard.jpg
                    comment: Keren Banget kak
                    created_at: 2022-09-11T09:40:00Z
                - postid: 2
                  foto: foto2.jpg
                  caption: foto di gunung salak
                  created_at: 2022-10-11T12:40:00Z
                  comments:
                  - commentid: 3
                    firstname: Jenny
                    lastname: Nyamuk
                    fotoprofil: jenny.jpg
                    comment: Indah sekali kak
                    created_at: 2022-09-11T12:40:00Z
                  - commentid: 4
                    firstname: Gerrad
                    lastname: Beruang
                    fotoprofil: Gerrard.jpg
                    comment: Biasa aja lah
                    created_at: 2022-09-11T09:40:00Z
                code: 200
                message: get data success
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
      security:
      - bearerAuth: []
    put:
      tags:
      - User
      summary: ini fitur update data user
      description: Update data user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModelUser'
            example:
              firstname: Tono
              lastname: Kumbang
              email: Tono@alterra.id
              username: Apple123
              password: Tono123
              birthdate: 1995-09-12T00:00:00.000+0000
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelUser'
              example:
                code: 200
                message: Success update data
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelUser'
              example:
                code: 400
                message: Wrong Input
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
      security:
      - bearerAuth: []
    post:
      tags:
      - User
      summary: ini fitur register
      description: Menambahkan data user baru
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModelUser'
            example:
              firstname: Albert
              lastname: Jerapah
              email: Albert@alterra.id
              username: Albertsss
              password: Albert123
              birthdate: 1990-10-20T00:00:00.000+0000
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelUser'
              example:
                code: 200
                message: Register success
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelUser'
              example:
                code: 400
                message: Wrong input
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
    delete:
      tags:
      - User
      summary: ini fitur hapus data user
      description: Hapus data user sesuai id
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: string
              example: '{"code":200,"message":"Success delete data"}'
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
      security:
      - bearerAuth: []
  /user/{username}:
    get:
      tags:
      - User
      summary: ini fitur cari data user
      description: Tampilkan data user sesuai id
      parameters:
      - name: username
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelUser'
              example:
                id: 1
                fotoprofil: alex.jpg
                firstname: Alex
                lastname: Capung
                username: DragonAlex
                posts:
                - postid: 1
                  foto: foto.jpg
                  caption: Rusia menyalakan bom nuklir, begini tanggapan Lesti Billar
                  created_at: 2022-09-11T12:40:00Z
                  comments:
                  - commentid: 1
                    firstname: Jenny
                    lastname: Nyamuk
                    fotoprofil: jenny.jpg
                    comment: Bagus Banget kak
                    created_at: 2022-09-11T12:40:00Z
                  - commentid: 2
                    firstname: Gerrad
                    lastname: Beruang
                    fotoprofil: Gerrard.jpg
                    comment: Keren Banget kak
                    created_at: 2022-09-11T09:40:00Z
                - postid: 2
                  foto: foto2.jpg
                  caption: foto di gunung salak
                  created_at: 2022-10-11T12:40:00Z
                  comments:
                  - commentid: 3
                    firstname: Jenny
                    lastname: Nyamuk
                    fotoprofil: jenny.jpg
                    comment: Indah sekali kak
                    created_at: 2022-09-11T12:40:00Z
                  - commentid: 4
                    firstname: Gerrad
                    lastname: Beruang
                    fotoprofil: Gerrard.jpg
                    comment: Biasa aja lah
                    created_at: 2022-09-11T09:40:00Z
                code: 200
                message: get data success
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
  /posts:
    get:
      tags:
      - Posting
      summary: ini fitur lihat semua posting
      description: Menampilkan seluruh post
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ModelPosting'
              example:
              - id: 1
                firstname: Alex
                lastname: Capung
                username: DragonAlex
                fotoprofil: alex.jpg
                foto: foto.jpg
                caption: Rusia menyalakan bom nuklir, begini tanggapan Lesti Billar
                created_at: 2022-09-11T12:40:00Z
                comments:
                - commentid: 1
                  firstname: Jenny
                  lastname: Nyamuk
                  fotoprofil: jenny.jpg
                  comment: Bagus Banget kak
                  created_at: 2022-09-11T12:40:00Z
                - commentid: 2
                  firstname: Gerrad
                  lastname: Beruang
                  fotoprofil: Gerrard.jpg
                  comment: Keren Banget kak
                  created_at: 2022-09-11T09:40:00Z
              - id: 2
                userid: 1
                firstname: Alex
                lastname: Capung
                username: DragonAlex
                fotoprofil: alex.jpg
                foto: foto2.jpg
                caption: foto di gunung salak
                created_at: 2022-10-11T12:40:00Z
                comments:
                - commentid: 3
                  firstname: Jenny
                  lastname: Nyamuk
                  fotoprofil: jenny.jpg
                  comment: Indah sekali kak
                  created_at: 2022-09-11T12:40:00Z
                - commentid: 4
                  firstname: Gerrad
                  lastname: Beruang
                  fotoprofil: Gerrard.jpg
                  comment: Biasa aja lah
                  created_at: 2022-09-11T09:40:00Z
              - code: 200
                message: get data success
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
  /post:
    put:
      tags:
      - Posting
      summary: ini fitur update post
      description: Update data post sesuai id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModelPosting'
            example:
              userid: 1
              fotoprofil: alex.jpg
              foto: foto.jpg
              caption: Rusia menyalakan bom nuklir, begini tanggapan Lesti Billar
        required: true
      responses:
        "200":
          description: Success update user data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelUser'
              example:
                code: 200
                message: Success update post
        "400":
          description: Invalid Input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelUser'
              example:
                code: 400
                message: Wrong input
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
      security:
      - bearerAuth: []
    post:
      tags:
      - Posting
      summary: ini fitur tambah posting
      description: Menambahkan post baru
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModelPosting'
            example:
              userid: 1
              fotoprofil: alex.jpg
              foto: foto.jpg
              caption: Rusia menyalakan bom nuklir, begini tanggapan Lesti Billar
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelPosting'
              example:
                code: 200
                message: Success creating a post
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelPosting'
              example:
                code: 400
                message: Wrong input
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
      security:
      - bearerAuth: []
    delete:
      tags:
      - Posting
      summary: ini fitur hapus post
      description: Hapus data user sesuai id
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: string
              example: '{"code":200,"message":"Success delete post"}'
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
      security:
      - bearerAuth: []
  /comments:
    get:
      tags:
      - Comment
      summary: ini fitur lihat komen
      description: Menampilkan seluruh data comment
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ModelComment'
              example:
              - id: 1
                firstname: Jenny
                lastname: Nyamuk
                fotoprofil: jenny.jpg
                postid: 1
                comment: Bagus Banget kak
                created_at: 2022-09-11T12:40:00Z
              - id: 2
                firstname: Gerrad
                lastname: Beruang
                fotoprofil: Gerrard.jpg
                postid: 1
                comment: Keren Banget kak
                created_at: 2022-09-11T09:40:00Z
              - code: 200
                message: get data success
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
  /comment:
    post:
      tags:
      - Comment
      summary: ini fitur tambah komen
      description: Menambahkan comment baru
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModelComment'
            example:
              userid: 1
              postid: 1
              comment: Bagus Banget kak
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelPosting'
              example:
                code: 200
                message: Success creating a comment
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelPosting'
              example:
                code: 400
                message: Wrong input
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
      security:
      - bearerAuth: []
    delete:
      tags:
      - Comment
      summary: ini fitur hapus komen
      description: Hapus komen user yang login
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: string
              example: '{"code":200,"message":"Success delete comment"}'
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
      security:
      - bearerAuth: []
components:
  schemas:
    ModelUser:
      type: object
      properties:
        id:
          type: integer
          format: int32
        fotoprofil:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
          format: email
        username:
          type: string
        password:
          type: string
        birthdate:
          type: string
          format: date
        token:
          type: string
        posts:
          type: array
          items:
            $ref: '#/components/schemas/ModelUser_posts'
    ModelPosting:
      type: object
      properties:
        id:
          type: integer
          format: int32
        firstname:
          type: string
        lastname:
          type: string
        username:
          type: string
        fotoprofil:
          type: string
        foto:
          type: string
        caption:
          type: string
        created_at:
          type: string
          format: date-time
        comments:
          type: array
          items:
            $ref: '#/components/schemas/ModelUser_comments'
    ModelComment:
      type: object
      properties:
        id:
          type: integer
          format: int32
        username:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        fotoprofil:
          type: string
        postid:
          type: integer
          format: int32
        comment:
          type: string
        created_at:
          type: string
          format: date-time
    ModelUser_comments:
      type: object
      properties:
        commentid:
          type: string
        username:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        fotoprofil:
          type: string
        comment:
          type: string
        created_at:
          type: string
          format: date-time
      example: null
    ModelUser_posts:
      type: object
      properties:
        postid:
          type: integer
          format: int32
        foto:
          type: string
        caption:
          type: string
        created_at:
          type: string
          format: date-time
        comments:
          type: array
          items:
            $ref: '#/components/schemas/ModelUser_comments'
      example: null
  responses:
    "404":
      description: Data Not Found
      content:
        application/json:
          schema:
            type: string
          example: '{"code":404,"message":"Data not found"}'
    "500":
      description: Internal server Error
      content:
        application/json:
          schema:
            type: string
          example: '{"code":500,"message":"There is an error in internal server"}'
  securitySchemes:
    bearerAuth:
      type: http
      description: JWT Authentication
      scheme: bearer
      bearerFormat: JWT
